version: 2.1

executors:
  my-executor:
    docker:
      - image: cimg/base:stable
    circleci_ip_ranges: true

jobs:
  build:
    executor: my-executor
    steps:
      - checkout
      - run: echo "hello"
